development: &default
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: docker
  password: docker
  host: <%= ENV.fetch('INVENTORYDB_PORT_5432_TCP_ADDR') %>
  port: <%= ENV.fetch('INVENTORYDB_PORT_5432_TCP_PORT') %>

test:
  <<: *default
  database: myapp_test

